---
title: "Cholera outbreak in Yemen, 2017: simple model fits"
author: "Lucy M. Li"
date: "Nov 21, 2017"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Background Information



## Data

```{r libraries}
library(tidyverse)
library(lubridate)
library(magrittr)
library(ggmap)
library(gridExtra)
library(gganimate)
source("simple-model-fits.R")
```

```{r data, cache=TRUE}
# Read in shapefile data
spatial <- list()
spatial$map <- readRDS("../data/yemen_map.rds")
spatial$shp <- readRDS("../data/yemen_shp.rds")
spatial$info <- readRDS("../data/yemen_shp_info.rds")
# Read in daily timeseries and aggregate data into weeks
timeseries <- list()
timeseries$national <- readRDS("../data/timeseries-national.rds")
timeseries$governorate <- readRDS("../data/timeseries-governorate.rds")
change.names <- levels(timeseries$governorate$Governorate) %>% `[`(!(.%in%spatial$info$admin1Name_en))
timeseries$governorate$Governorate %<>% 
  as.character() %>%
  sapply(function (x) ifelse(x %in% change.names, "Hadramaut", x)) %>% 
  factor()
timeseries$national.weekly <- aggregate.by.week(timeseries$national)
timeseries$governorate.weekly <- aggregate.by.week(timeseries$governorate)
```


```{r combinedata, cache=TRUE}
spatiotemporal.governorate <- 
  lapply(unique(timeseries$governorate.weekly$aggDate)[-1],
         function (x) combine.spatiotemporal(spatial, timeseries$governorate.weekly, x)) %>%
  do.call(what=rbind)
```

```{r DataPlotsNational}
plot.weekly.ts(timeseries$national.weekly, title="Incidence of cholera in Yemen")
```

```{r DataPlotsGovernorate, fig.width=10, fig.height=15}
plot.weekly.ts(timeseries$governorate.weekly, 
               title="Incidence of cholera in Yemen governorates") +
  facet_wrap(~Governorate, ncol=3)
```


```{r SpatialPlotsGovernorate, fig.show = "animate", fig.width=diff(range(spatial$shp$long))*0.7, fig.height=diff(range(spatial$shp$lat))*0.7}
gganimate(plot.spatiotemporal(spatiotemporal.governorate), title_frame=FALSE)
```



